/***********************************************************************************************************************
Date		: 21-Sept-2018
*********************************************************************************************************************/

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('[dbo].[DOAA1_INFO_UPDATE]','P') IS NOT NULL
BEGIN
	DROP PROCEDURE [dbo].[DOAA1_INFO_UPDATE]
END
GO

CREATE PROCEDURE [dbo].[DOAA1_INFO_UPDATE]
	@IDNo INT ,
	@DataCaptYM int,
	@DeptID nvarchar(10),
	@MenuID nvarchar(10),
	@DataUser nvarchar(50),	
	@DataStatus smallint,
	@DataStatusLog nvarchar(max),
	@DataValid char(1),
	@DataLocked char(1),
	@stMaleUGFT int,
	@stMaleUG5FT int,
	@stMalePGFT int,
	@stMalePGPT int,
	@stFemaleUGFT int,
	@stFemaleUG5FT int,
	@stFemalePGFT int,
	@stFemalePGPT int,
	@stTotalWithinStateUGFT int,
	@stTotalWithinStateUG5FT int,
	@stTotalWithinStatePGFT int,
	@stTotalWithinStatePGPT int,
	@stTotalOutsideStateUGFT int,
	@stTotalOutsideStateUG5FT int,
	@stTotalOutsideStatePGFT int,
	@stTotalOutsideStatePGPT int,
	@stTotalForeignUGFT int,
	@stTotalForeignUG5FT int,
	@stTotalForeignPGFT int,
	@stTotalForeignPGPT int,
	@stEcoBackMaleUGFT int,
	@stEcoBackMaleUG5FT int,
	@stEcoBackMalePGFT int,
	@stEcoBackMalePGPT int,
	@stSocChaFemaleUGFT int,
	@stSocChaFemaleUG5FT int,
	@stSocChaFemalePGFT int,
	@stSocChaFemalePGPT int,
	@stSocChaMaleUGFT int,
	@stSocChaMaleUG5FT int,
	@stSocChaMalePGFT int,
	@stSocChaMalePGPT int,
	@stPHFemaleUGFT int,
	@stPHFemaleUG5FT int,
	@stPHFemalePGFT int,
	@stPHFemalePGPT int,
	@stPHMaleUGFT int,
	@stPHMaleUG5FT int,
	@stPHMalePGFT int,
	@stPHMalePGPT int,
	@stScholarGovFemaleUGFT int,
	@stScholarGovFemaleUG5FT int,
	@stScholarGovFemalePGFT int,
	@stScholarGovFemalePGPT int,
	@stScholarGovMaleUGFT int,
	@stScholarGovMaleUG5FT int,
	@stScholarGovMalePGFT int,
	@stScholarGovMalePGPT int,
	@stScholorInstFemaleUGFT int,
	@stScholorInstFemaleUG5FT int,
	@stScholorInstFemalePGFT int,
	@stScholorInstFemalePGPT int,
	@stScholorInstMaleUGFT int,
	@stScholorInstMaleUG5FT int,
	@stScholorInstMalePGFT int,
	@stScholorInstMalePGPT int,
	@stScholorPvtFemaleUGFT int,
	@stScholorPvtFemaleUG5FT int,
	@stScholorPvtFemalePGFT int,
	@stScholorPvtFemalePGPT int,
	@stScholorPvtMaleUGFT int,
	@stScholorPvtMaleUG5FT int,
	@stScholorPvtMalePGFT int,
	@stScholorPvtMalePGPT int,
	@stNoScholorMaleUGFT int,
	@stNoScholorMaleUG5FT int,
	@stNoScholorMalePGFT int,
	@stNoScholorMalePGPT int,
	@stIntakeMaleUGFT int,
	@stIntakeMaleUG5FT int,
	@stIntakeMalePGFT int,
	@stIntakeMalePGPT int,
	@stAdmitMaleUGFT int,
	@stAdmitMaleUG5FT int,
	@stAdmitMalePGFT int,
	@stAdmitMalePGPT int,
	@stLateralMaleUGFT int,
	@stLateralMaleUG5FT int,
	@stLateralMalePGFT int,
	@stLateralMalePGPT int,
	@stMinGradMaleUGFT int,
	@stMinGradMaleUG5FT int,
	@stMinGradMalePGFT int,
	@stMinGradMalePGPT int,
	@stPlaceMedSalMaleUGFT int,
	@stPlaceMedSalMaleUG5FT int,
	@stPlaceMedSalMalePGFT int,
	@stPlaceMedSalMalePGPT int,
	@stHigherMaleUGFT int,
	@stHigherMaleUG5FT int,
	@stHigherMalePGFT int,
	@stHigherMalePGPT int,
	@stConfNatMaleUGFT int,
	@stConfNatMaleUG5FT int,
	@stConfNatMalePGFT int,
	@stConfNatMalePGPT int,
	@stConfIntMaleUGFT int,
	@stConfIntMaleUG5FT int,
	@stConfIntMalePGFT int,
	@stConfIntMalePGPT int,
	@stPhDFT int,
	@stPhDPT int,
	@stGradPhDFT int,
	@stGradPhDPT int
AS
	DECLARE @DataUpdatedOn datetime = GETDATE()
    
    UPDATE [dbo].[stInfo] 
	SET
           DataCaptYM = @DataCaptYM, 
           DeptID = @DeptID,
           MenuID = @MenuID,
           DataUser = @DataUser,
           DataUpdatedOn = @DataUpdatedOn,
           DataStatus = @DataStatus,
           DataStatusLog = @DataStatusLog,
           DataValid = @DataValid,
           DataLocked = @DataLocked,
           stMaleUGFT = @stMaleUGFT, 
           stMaleUG5FT = @stMaleUG5FT, 
           stMalePGFT = @stMalePGFT, 
           stMalePGPT = @stMalePGPT, 
           stFemaleUGFT = @stFemaleUGFT, 
           stFemaleUG5FT = @stFemaleUG5FT, 
           stFemalePGFT = @stFemalePGFT, 
           stFemalePGPT = @stFemalePGPT, 
           stTotalWithinStateUGFT = @stTotalWithinStateUGFT,
           stTotalWithinStateUG5FT = @stTotalWithinStateUG5FT,
           stTotalWithinStatePGFT = @stTotalWithinStatePGFT,
           stTotalWithinStatePGPT = @stTotalWithinStatePGPT,
           stTotalOutsideStateUGFT = @stTotalOutsideStateUGFT, 
           stTotalOutsideStateUG5FT = @stTotalOutsideStateUG5FT, 
           stTotalOutsideStatePGFT = @stTotalOutsideStatePGFT, 
           stTotalOutsideStatePGPT = @stTotalOutsideStatePGPT, 
           stTotalForeignUGFT = @stTotalForeignUGFT, 
           stTotalForeignUG5FT = @stTotalForeignUG5FT, 
           stTotalForeignPGFT = @stTotalForeignPGFT, 
           stTotalForeignPGPT = @stTotalForeignPGPT, 
           stEcoBackMaleUGFT = @stEcoBackMaleUGFT, 
           stEcoBackMaleUG5FT = @stEcoBackMaleUG5FT, 
           stEcoBackMalePGFT = @stEcoBackMalePGFT, 
           stEcoBackMalePGPT = @stEcoBackMalePGPT, 
           stSocChaFemaleUGFT = @stSocChaFemaleUGFT, 
           stSocChaFemaleUG5FT = @stSocChaFemaleUG5FT, 
           stSocChaFemalePGFT = @stSocChaFemalePGFT, 
           stSocChaFemalePGPT = @stSocChaFemalePGPT, 
           stSocChaMaleUGFT = @stSocChaMaleUGFT, 
           stSocChaMaleUG5FT = @stSocChaMaleUG5FT, 
           stSocChaMalePGFT = @stSocChaMalePGFT, 
           stSocChaMalePGPT = @stSocChaMalePGPT, 
           stPHFemaleUGFT = @stPHFemaleUGFT, 
           stPHFemaleUG5FT = @stPHFemaleUG5FT, 
           stPHFemalePGFT = @stPHFemalePGFT, 
           stPHFemalePGPT = @stPHFemalePGPT, 
           stPHMaleUGFT = @stPHMaleUGFT, 
           stPHMaleUG5FT = @stPHMaleUG5FT, 
           stPHMalePGFT = @stPHMalePGFT, 
           stPHMalePGPT = @stPHMalePGPT, 
           stScholarGovFemaleUGFT =	@stScholarGovFemaleUGFT, 
           stScholarGovFemaleUG5FT =	@stScholarGovFemaleUG5FT, 
           stScholarGovFemalePGFT =	@stScholarGovFemalePGFT, 
           stScholarGovFemalePGPT =	@stScholarGovFemalePGPT, 
           stScholarGovMaleUGFT =	@stScholarGovMaleUGFT, 
           stScholarGovMaleUG5FT =	@stScholarGovMaleUG5FT, 
           stScholarGovMalePGFT =	@stScholarGovMalePGFT, 
           stScholarGovMalePGPT =	@stScholarGovMalePGPT, 
           stScholorInstFemaleUGFT =	@stScholorInstFemaleUGFT, 
           stScholorInstFemaleUG5FT = @stScholorInstFemaleUG5FT, 
           stScholorInstFemalePGFT =	@stScholorInstFemalePGFT, 
           stScholorInstFemalePGPT =	@stScholorInstFemalePGPT, 
           stScholorInstMaleUGFT =	@stScholorInstMaleUGFT, 
           stScholorInstMaleUG5FT =	@stScholorInstMaleUG5FT, 
           stScholorInstMalePGFT =	@stScholorInstMalePGFT, 
           stScholorInstMalePGPT =	@stScholorInstMalePGPT, 
           stScholorPvtFemaleUGFT =	@stScholorPvtFemaleUGFT, 
           stScholorPvtFemaleUG5FT =	@stScholorPvtFemaleUG5FT, 
           stScholorPvtFemalePGFT =	@stScholorPvtFemalePGFT, 
           stScholorPvtFemalePGPT =	@stScholorPvtFemalePGPT, 
           stScholorPvtMaleUGFT =	@stScholorPvtMaleUGFT, 
           stScholorPvtMaleUG5FT = @stScholorPvtMaleUG5FT, 
           stScholorPvtMalePGFT = @stScholorPvtMalePGFT, 
           stScholorPvtMalePGPT = @stScholorPvtMalePGPT, 
           stNoScholorMaleUGFT =	@stNoScholorMaleUGFT, 
           stNoScholorMaleUG5FT = @stNoScholorMaleUG5FT, 
           stNoScholorMalePGFT =	@stNoScholorMalePGFT, 
           stNoScholorMalePGPT =	@stNoScholorMalePGPT, 
           stIntakeMaleUGFT = @stIntakeMaleUGFT, 
           stIntakeMaleUG5FT = @stIntakeMaleUG5FT, 
           stIntakeMalePGFT = @stIntakeMalePGFT, 
           stIntakeMalePGPT = @stIntakeMalePGPT, 
           stAdmitMaleUGFT =	 @stAdmitMaleUGFT, 
           stAdmitMaleUG5FT = @stAdmitMaleUG5FT, 
           stAdmitMalePGFT =	 @stAdmitMalePGFT, 
           stAdmitMalePGPT =	 @stAdmitMalePGPT, 
           stLateralMaleUGFT = @stLateralMaleUGFT, 
           stLateralMaleUG5FT =	@stLateralMaleUG5FT, 
           stLateralMalePGFT = @stLateralMalePGFT, 
           stLateralMalePGPT = @stLateralMalePGPT, 
           stMinGradMaleUGFT = @stMinGradMaleUGFT, 
           stMinGradMaleUG5FT = @stMinGradMaleUG5FT, 
           stMinGradMalePGFT = @stMinGradMalePGFT, 
           stMinGradMalePGPT = @stMinGradMalePGPT, 
           stPlaceMedSalMaleUGFT = @stPlaceMedSalMaleUGFT, 
           stPlaceMedSalMaleUG5FT = @stPlaceMedSalMaleUG5FT, 
           stPlaceMedSalMalePGFT = @stPlaceMedSalMalePGFT, 
           stPlaceMedSalMalePGPT = @stPlaceMedSalMalePGPT, 
           stHigherMaleUGFT =	@stHigherMaleUGFT, 
           stHigherMaleUG5FT =	@stHigherMaleUG5FT, 
           stHigherMalePGFT =	@stHigherMalePGFT, 
           stHigherMalePGPT =	@stHigherMalePGPT, 
           stConfNatMaleUGFT =	@stConfNatMaleUGFT, 
           stConfNatMaleUG5FT =	@stConfNatMaleUG5FT, 
           stConfNatMalePGFT =	@stConfNatMalePGFT, 
           stConfNatMalePGPT =	@stConfNatMalePGPT, 
           stConfIntMaleUGFT =	@stConfIntMaleUGFT, 
           stConfIntMaleUG5FT =	@stConfIntMaleUG5FT, 
           stConfIntMalePGFT =	@stConfIntMalePGFT, 
           stConfIntMalePGPT =	@stConfIntMalePGPT,
		   stPhDFT = @stPhDFT,
		   stPhDPT = @stPhDPT,
		   stGradPhDFT = @stGradPhDFT,
		   stGradPhDPT = @stGradPhDPT
     WHERE IDNo = @IDNo
      
      
GO

