<?xml version="1.0" encoding="utf-8"?><Database Name="RANK" Class="DataCollectionModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PC;Initial Catalog=RANK;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Depts" Member="Depts">
    <Type Name="Dept">
      <Column Name="SNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DeptID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DeptName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DeptType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DeptCAT" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserRole" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="UserRole" Member="UserRole1" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserRoleDetails" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserWork" Member="UserWorks">
    <Type Name="UserWork">
      <Column Name="UserWork" Member="UserWork1" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserWorkDetails" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserMenu" Member="UserMenus">
    <Type Name="UserMenu">
      <Column Name="UserMenuID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MenuID" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RankMesg" Member="RankMesgs">
    <Type Name="RankMesg">
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MenuIDs" Member="MenuIDs">
    <Type Name="MenuID">
      <Column Name="MenuID" Member="MenuID1" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MenuDetails" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MenuUrl" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RankUsers" Member="RankUsers">
    <Type Name="RankUser">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserPassword" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UserEmpNo" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DeptID" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="UserRole" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UserWork" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UserMob" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="UserEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserValid" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="UserCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserDisabledOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserRemarks" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IsEmailVerified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ActivationCode" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ResetPasswordCode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>