<?xml version="1.0" encoding="utf-8"?><Database Name="RANK1" Class="DataCollectionModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PC;Initial Catalog=RANK1;Integrated Security=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Depts" Member="Depts">
    <Type Name="Dept">
      <Column Name="SNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DeptID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DeptName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DeptType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DeptCAT" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserRole" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="UserRole" Member="UserRole1" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserRoleDetails" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserWork" Member="UserWorks">
    <Type Name="UserWork">
      <Column Name="UserWork" Member="UserWork1" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserWorkDetails" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserMenu" Member="UserMenus">
    <Type Name="UserMenu">
      <Column Name="UserMenuID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MenuID" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RankUsers" Member="RankUsers">
    <Type Name="RankUser">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserPassword" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UserEmpNo" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DeptID" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="UserRole" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UserWork" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UserMob" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="UserEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserValid" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="UserCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserDisabledOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserRemarks" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IsEmailVerified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ActivationCode" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ResetPasswordCode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MenuIDs" Member="MenuIDs">
    <Type Name="MenuID">
      <Column Name="MenuID" Member="MenuID1" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MenuDetails" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MenuUrl" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsAdminMenu" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RankMesg" Member="RankMesgs">
    <Type Name="RankMesg">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DofaPeer" Member="DofaPeers">
    <Type Name="DofaPeer">
      <Column Name="IDNo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DataCaptYM" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DeptID" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MenuID" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataUser" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DataUpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DataStatus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DataStatusLog" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DataValid" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DataLocked" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="empNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PeerNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PeerType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PeerTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PeerFName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PeerLName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PeerJob" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PeerDept" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PeerInst" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PeerCountry" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PeerEmail" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PeerMob" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PeerDetails" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PeerRemarks" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.dofaInfo" Member="dofaInfos">
    <Type Name="dofaInfo">
      <Column Name="IDNo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DataCaptYM" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DeptID" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MenuID" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataUser" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DataUpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DataStatus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DataStatusLog" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DataValid" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DataLocked" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="empNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="empName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="empDOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="empDOR" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="empDOJ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="empDOL" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="empGender" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="empDESG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="empDEPT" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="empPAN" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="empType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="empCat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="empNation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QualHighYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QualHighCourse" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="QualHighInst" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ExpAcadMon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExpIndMon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FacExcgIn" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="FacExcgOut" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ConfSymSemNat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConfSymSemInt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AwardHonors" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FinInfo" Member="FinInfos">
    <Type Name="FinInfo">
      <Column Name="IDNo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DataCaptYM" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DeptID" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MenuID" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataUser" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DataUpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DataStatus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DataStatusLog" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DataValid" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DataLocked" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FinYear" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ExpCapAAR" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ExpLibOverall" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ExpLibEngg" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ExpLibMgmt" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ExpLibArch" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ExpNewEqpLabs" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ExpEnggWS" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ExpStudios" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ExpOtherCapAssets" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ExpOperational" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ExpMaintRun" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ExpSalT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ExpSalNT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ExpMisc1" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ExpMisc2" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ExpTotal" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ExpRemarks" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SchFsUGFT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SchFsUG5FT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SchFsPGFT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SchFsPGPT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SchSSUGFT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SchSSUG5FT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SchSSPGFT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SchSSPGPT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SchTotal" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SchRemarks" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.Get_All_Table" Method="Get_All_Table">
    <ElementType Name="Get_All_TableResult">
      <Column Name="Name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>